/**
 * Backend string tokens / Chinese messages → i18n keys.
 * Token patterns (SCREAMING_SNAKE) are applied for every locale;
 * Chinese prose patterns are only used when locale is not zh-CN.
 */
export const API_ERROR_TOKEN_PATTERNS: readonly { pattern: RegExp; key: string }[] = [
  { pattern: /PITY_COMPENSATE_DENIED/, key: "api.errors.pityCompensateDenied" },
  { pattern: /PITY_STOCK_EXHAUSTED/, key: "api.errors.pityStockExhausted" },
  { pattern: /GENERAL_POOL_SOLD_OUT/, key: "api.errors.generalPoolSoldOut" },
  { pattern: /EV_GATE/, key: "api.errors.evGateRejected" },
  { pattern: /REFUND_IN_PROGRESS/, key: "api.errors.refundInProgress" },
  { pattern: /REFUND_DENIED/, key: "api.errors.refundDenied" },
  { pattern: /PAYMENT_AMOUNT_MISMATCH/, key: "api.errors.paymentAmountMismatch" },
  { pattern: /ORDER_OWNERSHIP_DENIED/, key: "api.errors.orderOwnershipDenied" },
  { pattern: /STOCK_CONFLICT/, key: "api.errors.stockConflict" },
  { pattern: /TEAM_LOTTERY_UNPAID/, key: "api.errors.teamLotteryUnpaid" },
  { pattern: /TEAM_LOTTERY_/, key: "api.errors.teamLotteryError" },
  { pattern: /MARKETPLACE_GATEWAY_NOT_READY/, key: "api.errors.marketplaceGatewayNotReady" },
  { pattern: /MARKETPLACE_LISTING_UNAVAILABLE/, key: "api.errors.marketplaceListingUnavailable" },
  { pattern: /MARKETPLACE_INSUFFICIENT_BALANCE/, key: "api.errors.marketplaceInsufficientBalance" },
  { pattern: /MARKETPLACE_COOLING/, key: "api.errors.marketplaceCooling" },
  { pattern: /MARKETPLACE_UNAUTHORIZED/, key: "api.errors.marketplaceUnauthorized" },
  { pattern: /MARKETPLACE_/, key: "api.errors.marketplaceError" },
  { pattern: /REVEAL_SPECTATOR_EXPIRED|观战链接已失效|观战链接已过期/, key: "spectator.expired" },
  { pattern: /REVEAL_SPECTATOR_NOT_FOUND|暂无观战链接/, key: "api.errors.notFound" },
  { pattern: /REVEAL_SPECTATOR_FORBIDDEN|观战链接已失效或无权更新/, key: "api.errors.forbidden" },
  { pattern: /PHONE_ALREADY_BOUND/, key: "api.errors.phoneAlreadyBound" },
  { pattern: /LOGIN_LOCKED|登录尝试过多/, key: "api.errors.loginLocked" },
  { pattern: /IOS_DIGITAL_GOODS_BLOCKED/, key: "api.errors.iosDigitalGoodsBlocked" },
];

/** Map common backend Chinese messages to i18n keys (used when locale is not zh-CN). */
export const API_ERROR_MESSAGE_PATTERNS: readonly { pattern: RegExp; key: string }[] = [
  { pattern: /订单不存在/, key: "api.errors.orderNotFound" },
  { pattern: /盲盒不存在/, key: "api.errors.boxNotFound" },
  { pattern: /用户不存在/, key: "api.errors.userNotFound" },
  { pattern: /优惠券/, key: "api.errors.couponInvalid" },
  { pattern: /验证码错误/, key: "api.errors.verifyCodeInvalid" },
  { pattern: /密码/, key: "api.errors.authFailed" },
  { pattern: /登录尝试过多|稍后再试.*登录|LOGIN_LOCKED/, key: "api.errors.loginLocked" },
  { pattern: /未登录|未授权|登录/, key: "api.errors.unauthorized" },
  { pattern: /无权操作|无权|非本人/, key: "api.errors.forbidden" },
  { pattern: /操作过于频繁|请勿重复/, key: "api.errors.rateLimited" },
  { pattern: /退款申请处理中|已有退款/, key: "api.errors.refundInProgress" },
  { pattern: /不可申请退款/, key: "api.errors.refundDenied" },
  { pattern: /订单状态/, key: "api.errors.orderStatusInvalid" },
  { pattern: /兑换商品|奖品不存在|已分解|数据不存在|不存在/, key: "api.errors.notFound" },
  { pattern: /并发冲突/, key: "api.errors.stockConflict" },
  { pattern: /库存|不足/, key: "api.errors.outOfStock" },
  { pattern: /账号已被封禁|封禁/, key: "api.errors.accountBanned" },
  { pattern: /PHONE_ALREADY_BOUND|当前账号已绑定手机号/, key: "api.errors.phoneAlreadyBound" },
  { pattern: /该手机号已被其他账号使用/, key: "api.errors.phoneTaken" },
  { pattern: /平台未启用消费限额/, key: "api.errors.spendLimitDisabled" },
  { pattern: /已超出每日消费限额/, key: "api.errors.spendLimitDailyExceeded" },
  { pattern: /已超出每月消费限额/, key: "api.errors.spendLimitMonthlyExceeded" },
  { pattern: /消费限额变更冷静期/, key: "api.errors.spendLimitCoolingOff" },
  { pattern: /限额必须大于/, key: "api.errors.spendLimitMustPositive" },
  { pattern: /限额不能超过平台上限/, key: "api.errors.spendLimitOverCap" },
  { pattern: /MoMo\s*退款通道未开通/, key: "api.errors.momoRefundUnavailable" },
  { pattern: /参数错误|参数有误|参数非法/, key: "api.errors.paramInvalid" },
  { pattern: /仅年满\s*18|年满 18 周岁/, key: "api.errors.ageMustBe18" },
  { pattern: /请先确认已满\s*18|请先确认已满 18/, key: "api.errors.ageRequired" },
  ...API_ERROR_TOKEN_PATTERNS,
];
