import { StyleSheet } from "react-native";
import { layout, radius, shadows, spacing, typography, font } from "../../styles/tokens";
import type { ThemeColors } from "../../styles/themes";

export function buildProfileStyles(colors: ThemeColors) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.bgPage },
    scroll: {
      paddingHorizontal: spacing.lg,
      paddingBottom: layout.screenPaddingBottom,
      gap: spacing.md,
    },
    heroBlock: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.md,
      paddingBottom: spacing.xs,
    },
    avatar: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: colors.bgCard,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: colors.profileHeaderDeep,
      overflow: "hidden",
      ...shadows.cardSm,
    },
    avatarImage: { width: "100%", height: "100%" },
    avatarText: { fontSize: typography.h2, fontWeight: "800", color: colors.brand },
    userInfo: { flex: 1 },
    loginChip: {
      backgroundColor: colors.brand,
      borderRadius: radius.pill,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.sm,
    },
    loginChipText: { color: colors.textOnBrand, fontWeight: "800", fontSize: typography.caption },
    userName: { ...font("bodySemiBold"), fontSize: typography.h3, fontWeight: "700", color: colors.textPrimary },
    collectorLine: {
      marginTop: 4,
      fontSize: typography.caption,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    honorMuted: {
      marginTop: 4,
      fontSize: typography.micro,
      color: colors.textMuted,
    },
    storyFragmentBadge: {
      alignSelf: "flex-start",
      marginTop: 4,
      paddingHorizontal: spacing.sm,
      paddingVertical: 2,
      borderRadius: radius.pill,
      backgroundColor: colors.bgBrandSoft,
      color: colors.brand,
      fontSize: typography.caption,
      fontWeight: "700",
    },
    honorError: {
      marginTop: 4,
      fontSize: typography.caption,
      color: colors.danger,
      fontWeight: "600",
    },
    userSub: { marginTop: spacing.xs, fontSize: typography.micro, color: colors.textMuted },
    walletRow: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.bgCard,
      borderRadius: radius.md,
      paddingVertical: spacing.md,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      ...shadows.cardSm,
    },
    walletCell: { flex: 1, alignItems: "center", paddingHorizontal: spacing.xs },
    pressablePressed: { opacity: 0.9 },
    walletDivider: { width: StyleSheet.hairlineWidth, alignSelf: "stretch", backgroundColor: colors.border, marginVertical: 4 },
    walletValue: { fontSize: typography.body, fontWeight: "800", color: colors.textPrimary },
    walletLabel: { marginTop: 2, fontSize: 10, color: colors.textMuted, fontWeight: "600" },
    balanceMeta: {
      textAlign: "center",
      fontSize: typography.micro,
      color: colors.textMuted,
      marginTop: spacing.xs,
    },
    balanceMetaLink: {
      textAlign: "center",
      fontSize: typography.micro,
      color: colors.brand,
      fontWeight: "700",
      marginTop: spacing.xs,
    },
    quickAccessCard: {
      backgroundColor: colors.bgCard,
      borderRadius: radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      paddingVertical: spacing.md,
      paddingHorizontal: spacing.sm,
      ...shadows.cardSm,
      gap: spacing.sm,
    },
    quickAccessTitle: {
      paddingHorizontal: spacing.sm,
      fontWeight: "800",
      fontSize: typography.caption,
      color: colors.textPrimary,
    },
    quickAccessRow: { flexDirection: "row", alignItems: "stretch" },
    quickAccessCell: { flex: 1, alignItems: "center", gap: spacing.xs, paddingVertical: spacing.xs },
    quickAccessIcon: {
      width: 40,
      height: 40,
      borderRadius: radius.md,
      backgroundColor: colors.bgBrandSoft,
      alignItems: "center",
      justifyContent: "center",
    },
    quickAccessLabel: {
      fontSize: typography.micro,
      fontWeight: "700",
      color: colors.textSecondary,
      textAlign: "center",
    },
    shelfBlock: { gap: spacing.sm },
    shelfTitle: { fontWeight: "800", fontSize: typography.body, color: colors.textPrimary },
    shelfRow: { gap: spacing.sm, paddingRight: spacing.md },
    shelfCard: {
      width: 100,
      backgroundColor: colors.bgCard,
      borderRadius: radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      overflow: "hidden",
      paddingBottom: spacing.xs,
    },
    shelfImage: { width: 100, height: 80, backgroundColor: colors.bgSoft },
    shelfImagePlaceholder: { alignItems: "center", justifyContent: "center" },
    shelfName: {
      marginTop: spacing.xs,
      marginHorizontal: spacing.xs,
      fontSize: typography.micro,
      fontWeight: "800",
      color: colors.textPrimary,
    },
    shelfTier: { marginHorizontal: spacing.xs, fontSize: typography.micro, color: colors.textMuted },
    achievementsBlock: { gap: spacing.xs },
    shareAchievementRow: { fontSize: typography.caption, color: colors.textSecondary },
    primaryCard: {
      backgroundColor: colors.bgCard,
      borderRadius: radius.lg,
      paddingVertical: spacing.md,
      paddingHorizontal: spacing.sm,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      ...shadows.cardSm,
    },
    primaryToolsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      gap: spacing.xs,
    },
    primaryTool: {
      flex: 1,
      minWidth: 0,
      alignItems: "center",
      paddingVertical: spacing.xs,
    },
    primaryIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: colors.bgBrandSoft,
      alignItems: "center",
      justifyContent: "center",
    },
    primaryToolLabel: {
      marginTop: spacing.xs,
      fontSize: typography.micro,
      fontWeight: "700",
      color: colors.textSecondary,
      textAlign: "center",
    },
    moreToolsHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.xs,
      flexShrink: 1,
    },
    moreToolsHint: {
      marginTop: spacing.xs,
      fontSize: typography.micro,
      color: colors.textMuted,
    },
    sectionCard: {
      backgroundColor: colors.bgCard,
      borderRadius: radius.lg,
      padding: spacing.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      ...shadows.cardSm,
    },
    sectionTitle: { fontWeight: "800", fontSize: typography.bodyLg, color: colors.textPrimary },
    sectionTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: spacing.md,
      gap: spacing.sm,
    },
    versionHint: { fontSize: typography.micro, color: colors.textMuted, fontWeight: "600" },
    versionRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
    checkUpdateBtn: {
      position: "relative",
      paddingHorizontal: spacing.sm,
      paddingVertical: 4,
      borderRadius: radius.pill,
      backgroundColor: colors.bgSoft,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    checkUpdateBtnPressed: { opacity: 0.85 },
    checkUpdateText: { fontSize: typography.micro, color: colors.brand, fontWeight: "700" },
    updateDot: {
      position: "absolute",
      top: -2,
      right: -2,
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.accent,
      borderWidth: 1,
      borderColor: colors.bgCard,
    },
    orderRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      gap: spacing.xs,
      marginBottom: spacing.md,
      paddingBottom: spacing.md,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    orderItem: {
      flex: 1,
      minWidth: 0,
      alignItems: "center",
      position: "relative",
      paddingVertical: spacing.xs,
      overflow: "visible",
    },
    orderLabel: {
      marginTop: spacing.xs,
      fontSize: 9,
      fontWeight: "700",
      color: colors.textSecondary,
      textAlign: "center",
    },
    orderBadge: {
      position: "absolute",
      top: -2,
      right: 0,
      minWidth: 16,
      paddingHorizontal: 3,
      height: 16,
      borderRadius: 8,
      backgroundColor: colors.accent,
      color: colors.textOnBrand,
      fontSize: 9,
      fontWeight: "800",
      textAlign: "center",
      overflow: "hidden",
      lineHeight: 14,
    },
    inviteCompact: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.sm,
      marginBottom: spacing.md,
      padding: spacing.md,
      borderRadius: radius.md,
      backgroundColor: colors.bgSoft,
    },
    inviteCompactLeft: { flex: 1, minWidth: 0 },
    inviteCompactTitle: { fontWeight: "700", fontSize: typography.caption, color: colors.textPrimary },
    inviteCompactMeta: { marginTop: 2, fontSize: typography.micro, color: colors.textMuted },
    inviteCompactCta: { color: colors.brand, fontWeight: "800", fontSize: typography.micro },
    guidedSection: {
      marginBottom: spacing.md,
      gap: spacing.xs,
    },
    guidedSectionTitle: {
      ...font("bodySemiBold"),
      fontSize: typography.caption,
      fontWeight: "700",
      color: colors.textSecondary,
      marginBottom: spacing.xs,
    },
    appGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing.xs,
      width: "100%",
    },
    appCell: {
      alignItems: "center",
      paddingVertical: spacing.sm,
      flexShrink: 0,
    },
    appIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 12,
      backgroundColor: colors.bgBrandSoft,
      alignItems: "center",
      justifyContent: "center",
    },
    appLabel: {
      marginTop: spacing.xs,
      fontSize: typography.micro,
      fontWeight: "600",
      color: colors.textSecondary,
      textAlign: "center",
    },
    logoutBtn: { marginTop: spacing.sm },
    modalMask: { flex: 1, backgroundColor: colors.overlay, justifyContent: "flex-end" },
    modalCard: {
      backgroundColor: colors.bgCard,
      borderTopLeftRadius: radius.xl,
      borderTopRightRadius: radius.xl,
      padding: spacing.xl,
      paddingBottom: spacing.xxl,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.card,
    },
    modalTitle: { fontWeight: "800", fontSize: typography.h4, marginBottom: spacing.md, color: colors.textPrimary },
    pickAvatarBtn: {
      marginTop: spacing.sm,
      paddingVertical: spacing.sm,
      alignItems: "center",
      borderRadius: radius.md,
      backgroundColor: colors.profileHeaderBg,
    },
    pickAvatarText: { color: colors.brand, fontWeight: "700", fontSize: typography.caption },
    modalActions: { flexDirection: "row", gap: spacing.md, marginTop: spacing.md },
    flexBtn: { flex: 1 },
  });
}
