CREATE TABLE IF NOT EXISTS user_notification_pref (
    user_id VARCHAR(32) NOT NULL PRIMARY KEY,
    order_enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'ORDER, PENDING_PAY',
    refund_enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'REFUND',
    warehouse_ship_enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'WAREHOUSE_SHIP',
    marketplace_enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'MARKETPLACE',
    marketing_enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'OPS_MESSAGE',
    updated_time DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);
