import { describe, expect, it, vi } from "vitest";
import { buildAppControllerLoadedSliceInput } from "./buildAppControllerLoadedSliceInput";

describe("buildAppControllerLoadedSliceInput", () => {
  it("maps runtime slices into mainTabs and shell input", () => {
    const noop = vi.fn();
    const input = buildAppControllerLoadedSliceInput({
      resetTo: noop,
      showOnboarding: false,
      dismissOnboarding: noop,
      authSession: {} as never,
      authHandlers: {} as never,
      nav: { view: "home", navigate: noop, resetTo: noop, goBack: noop, navigationEpoch: 0 },
      auth: { token: "t1", openLoginPage: noop, requireAuth: () => true, userProfile: null },
      wallet: {
        balance: 0,
        balanceUpdatedAtText: "",
        onRefreshBalance: async () => undefined,
        refreshingBalance: false,
        loadBalanceLogs: async () => undefined,
        balanceLogs: [],
        balanceLogsLoading: false,
        balanceLogsLoadError: null,
        refreshBalance: async () => undefined,
      },
      tabsShell: {
        orders: [],
        setGlobalErrors: noop,
        pageLoading: false,
        globalErrors: [],
        refreshAllWithLoading: async () => undefined,
        warehousePendingCount: 0,
      },
      catalog: {
        boxes: [],
        mallBoxes: [],
        mallCategoryId: undefined,
        mallKeyword: undefined,
        boxesLoadError: null,
        mallLoadError: null,
        activeBox: null,
        setActiveBox: noop,
        loadMallBoxes: async () => undefined,
        loadMoreBoxes: async () => undefined,
        loadMoreMallBoxes: async () => undefined,
        refreshMallCatalog: async () => undefined,
        setPageLoading: noop,
        hasMoreBoxes: false,
        hasMoreMallBoxes: false,
        loadingMoreBoxes: false,
        loadingMoreMallBoxes: false,
        handleMallCategoryChange: noop,
        handleMallSearch: noop,
        homeBanner: {},
        openDetailsPage: noop,
        selectedActivity: null,
        setSelectedActivity: noop,
      },
      catalogSearch: {
        openCatalogSearch: noop,
        catalogSearchInitialKeyword: "",
      },
      checkout: {
        addresses: [],
        addressesLoading: false,
        addressesLoadError: null,
        selectedAddressId: "",
        setSelectedAddressId: noop,
        creatingOrder: false,
        openAddressFormPage: noop,
        quote: null,
        quotingPrice: false,
        quoteError: null,
        retryQuote: noop,
        availableCoupons: [],
        selectedCouponUserId: "",
        setSelectedCouponUserId: noop,
        openAddressForm: noop,
        loadAddresses: async () => undefined,
        onSetDefaultAddress: noop,
        onDeleteAddress: noop,
        drawCount: 1,
        setDrawCount: noop,
        createOrder: noop,
        pendingCheckoutResume: false,
        setPendingCheckoutResume: noop,
        spendLimitRefreshKey: 0,
      },
      orderList: {
        selectedOrder: null,
        setSelectedOrder: noop,
        orders: [],
        loadOrders: async () => undefined,
        loadOrdersDebounced: noop,
        loadMoreOrders: async () => undefined,
        hasMoreOrders: false,
        loadingMoreOrders: false,
        requestPayment: async () => undefined,
        openOrderDetailsPage: noop,
        refreshOrderDetails: noop,
        cancelUnpaidOrder: noop,
        redeemToBalance: noop,
        confirmReceive: noop,
        isUnpaidOrder: () => false,
        orderStatusFilter: "ALL",
        autoRefreshOrders: false,
        orderKeyword: "",
        setOrderStatusFilter: noop,
        setAutoRefreshOrders: noop,
        setOrderKeyword: noop,
        searchedOrders: [],
        onFilterByStatus: noop,
        ordersLoadError: null,
        ordersReady: true,
      },
      account: {
        couponCount: 0,
        publicConfig: {
          supportHotline: "",
          enterpriseWechat: "",
          revealParticleScale: 1,
          revealConfettiScale: 1,
          revealDelayMsOverride: 0,
          revealChargeScale: 1,
          revealFlashScale: 1,
          revealLustreScale: 1,
          revealFeedTickerEnabled: true,
          revealInterDrawDelayMs: 450,
          revealFinalePauseMs: 600,
          revealFinaleHoldMsExtra: 300,
          revealFinaleTeaserEnabled: true,
          revealSilenceBeforeFinaleMs: 220,
          revealSummaryHeroMs: 1800,
          loading: false,
          loadError: null,
          reload: async () => undefined,
        },
        openFeaturePage: noop,
        unreadMessageCount: 0,
        refreshServerNotifications: noop,
        setReadNotificationIds: noop,
      },
      addressForm: {
        formRealName: "",
        formPhoneNumber: "",
        formRegion: "",
        formDetails: "",
        formHouseNumber: "",
        formDistrict: "",
        formWard: "",
        formIsDefault: false,
        setFormRealName: noop,
        setFormPhoneNumber: noop,
        setFormRegion: noop,
        setFormDetails: noop,
        setFormHouseNumber: noop,
        setFormDistrict: noop,
        setFormWard: noop,
        setFormIsDefault: noop,
        editingAddressId: null,
        savingAddress: false,
        saveAddress: noop,
      },
      shell: {
        token: "t1",
        newcomer: { visible: false, dismiss: noop, hide: noop, open: noop },
        openDetailsPage: noop,
        paymentShell: {} as never,
        executeMockPayment: async () => undefined,
        requestPayment: async () => undefined,
        payWithPrepay: async () => false,
        onPaymentConfirmed: async () => undefined,
        showAddressModal: false,
        setShowAddressModal: noop,
        editingAddressId: null,
        formRealName: "",
        formPhoneNumber: "",
        formRegion: "",
        formDetails: "",
        formHouseNumber: "",
        formDistrict: "",
        formWard: "",
        savingAddress: false,
        setFormRealName: noop,
        setFormPhoneNumber: noop,
        setFormRegion: noop,
        setFormDetails: noop,
        setFormHouseNumber: noop,
        setFormDistrict: noop,
        setFormWard: noop,
        resetForm: noop,
        saveAddress: noop,
        activeBox: null,
        setActiveBox: noop,
        navigate: noop,
        createOrder: noop,
        openOrderDetailsPage: noop,
      },
    });

    expect(input.mainTabs.nav.view).toBe("home");
    expect(input.mainTabs.shell.orders).toEqual([]);
    expect(input.mainTabs.orders.searchedOrders).toEqual([]);
    expect(input.shell.token).toBe("t1");
  });
});
