import type { Dispatch, SetStateAction } from "react";
import type { AppView } from "../components/mainTabs/appViews";
import type { TabKey } from "../components/ui/BottomTabBar";
import type { MysteryBoxActivity } from "../services/activityService";
import type { MysteryBox, Order, CouponItem, UserProfile } from "../types";
import type { PaymentPriceView } from "../types";
import type { NavigateOptions } from "./useAppNavigation";

export type MainTabsBuildInput = {
  view: AppView;
  navigate: (view: AppView, options?: NavigateOptions) => void;
  resetTo: (tab: AppView) => void;
  goBack: () => void;
  navigationEpoch: number;
  token: string;
  openLoginPage: () => void;
  requireAuth: (action?: () => void) => boolean;
  userProfile: UserProfile | null;
  balance: number;
  balanceUpdatedAtText: string;
  onRefreshBalance: (onError: (message: string) => void) => Promise<void>;
  refreshingBalance: boolean;
  loadBalanceLogs: (token: string) => Promise<void>;
  balanceLogs: import("../types").UserBalanceLog[];
  balanceLogsLoading: boolean;
  balanceLogsLoadError: string | null;
  setGlobalErrors: (messages: string[]) => void;
  pageLoading: boolean;
  globalErrors: string[];
  refreshAllWithLoading: (token: string, options?: { includeHeavy?: boolean; includeMall?: boolean }) => Promise<void>;
  orderBadges: ReturnType<typeof import("../utils/orderBadges").computeOrderBadges>;
  orderTabCounts: import("../utils/orderDisplayRows").OrderTabCounts;
  boxes: MysteryBox[];
  mallBoxes: MysteryBox[];
  mallCategoryId?: string;
  mallKeyword?: string;
  boxesLoadError: string | null;
  mallLoadError: string | null;
  ordersLoadError: string | null;
  activeBox: MysteryBox | null;
  setActiveBox: (box: MysteryBox | null) => void;
  addresses: import("../types").Address[];
  addressesLoading: boolean;
  addressesLoadError: string | null;
  selectedAddressId: string;
  setSelectedAddressId: (id: string) => void;
  creatingOrder: boolean;
  loadMallBoxes: (token: string, categoryId?: string, page?: number, keyword?: string) => Promise<void>;
  loadMoreBoxes: (token: string) => Promise<void>;
  loadMoreMallBoxes: (token: string) => Promise<void>;
  refreshMallCatalog: (token: string) => Promise<void>;
  setPageLoading: (value: boolean) => void;
  hasMoreBoxes: boolean;
  hasMoreMallBoxes: boolean;
  loadingMoreBoxes: boolean;
  loadingMoreMallBoxes: boolean;
  handleMallCategoryChange: (categoryId?: string) => void;
  handleMallSearch: (keyword: string) => void;
  homeBanner: { uri?: string; title?: string; subtitle?: string };
  openDetailsPage: (id: string) => void | Promise<void>;
  openAddressFormPage: (address?: import("../types").Address, resumeCheckout?: boolean) => void;
  quote: PaymentPriceView | null;
  quotingPrice: boolean;
  quoteError: string | null;
  availableCoupons: CouponItem[];
  selectedCouponUserId: string;
  setSelectedCouponUserId: (id: string) => void;
  openAddressForm: (address?: import("../types").Address) => void;
  loadAddresses: (token: string) => Promise<void>;
  onSetDefaultAddress: (id: string) => void | Promise<void>;
  onDeleteAddress: (id: string) => void;
  drawCount: number;
  setDrawCount: (count: number) => void;
  createOrder: (drawMode?: import("../services/orderService").DrawMode, slotNo?: number) => void;
  pendingCheckoutResume: boolean;
  setPendingCheckoutResume: (value: boolean) => void;
  spendLimitRefreshKey: number;
  selectedActivity: MysteryBoxActivity | null;
  setSelectedActivity: (activity: MysteryBoxActivity | null) => void;
  selectedOrder: Order | null;
  setSelectedOrder: (order: Order | null) => void;
  orders: Order[];
  ordersReady: boolean;
  loadOrders: (token: string) => Promise<void>;
  loadOrdersDebounced: (token: string) => void;
  loadMoreOrders: (token: string) => Promise<void>;
  hasMoreOrders: boolean;
  loadingMoreOrders: boolean;
  requestPayment: (orderId: string, payAmount?: number) => Promise<void>;
  openOrderDetailsPage: (id: string) => void | Promise<void>;
  refreshOrderDetails: (id: string) => void | Promise<void>;
  cancelUnpaidOrder: (orderId: string) => void | Promise<void>;
  redeemToBalance: (orderId: string) => void | Promise<void>;
  confirmReceive: (orderId: string) => void | Promise<void>;
  isUnpaidOrder: (order: Order) => boolean;
  orderStatusFilter: string;
  autoRefreshOrders: boolean;
  orderKeyword: string;
  setOrderStatusFilter: (status: string) => void;
  setAutoRefreshOrders: (value: boolean) => void;
  setOrderKeyword: (keyword: string) => void;
  searchedOrders: Order[];
  onFilterByStatus: (status: string) => void;
  refreshBalance: (token: string) => Promise<number | void>;
  couponCount: number;
  publicConfig: import("../services/appConfigService").AppPublicConfig & {
    loading: boolean;
    loadError: string | null;
    reload: () => Promise<void>;
  };
  openFeaturePage: (title: string) => void | Promise<void>;
  unreadMessageCount: number;
  warehousePendingCount: number;
  warehousePendingCountApproximate?: boolean;
  onTabFocus?: (tab: TabKey) => void;
  refreshServerNotifications: () => void | Promise<void>;
  setReadNotificationIds: Dispatch<SetStateAction<Set<string>>>;
  formRealName: string;
  formPhoneNumber: string;
  formRegion: string;
  formDistrict: string;
  formWard: string;
  formDetails: string;
  formHouseNumber: string;
  formIsDefault: boolean;
  setFormRealName: (v: string) => void;
  setFormPhoneNumber: (v: string) => void;
  setFormRegion: (v: string) => void;
  setFormDistrict: (v: string) => void;
  setFormWard: (v: string) => void;
  setFormDetails: (v: string) => void;
  setFormHouseNumber: (v: string) => void;
  setFormIsDefault: (v: boolean) => void;
  editingAddressId: string | null;
  savingAddress: boolean;
  saveAddress: () => void | Promise<void>;
  setPendingCheckoutResumeOnBack: () => void;
  openCatalogSearch: (keyword?: string) => void;
  catalogSearchInitialKeyword: string;
  communityDraft?: string;
  openCommunityWithDraft?: (draft: string) => void;
  openNewcomerOffer?: () => void;
  onLogout?: () => void | Promise<void>;
};
