import { StyleSheet } from "react-native";
import { useThemedStyles } from "../hooks/useThemedStyles";
import { layout, radius, shadows, spacing, typography } from "./tokens";
import type { ThemeColors } from "./themes";

export function buildAppStyles(colors: ThemeColors) {
  return StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: colors.bgPage,
  },
  pageFill: {
    flex: 1,
    backgroundColor: colors.bgPage,
  },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.bgPage,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.lg,
    backgroundColor: colors.bgCard,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.cardSm,
  },
  tabRow: { flexDirection: "row", gap: spacing.md, alignItems: "center" },
  tabBtn: {
    borderWidth: 1.5,
    borderColor: "transparent",
    borderRadius: radius.pill,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    backgroundColor: "transparent",
  },
  tabBtnActive: {
    borderColor: colors.brand,
    backgroundColor: colors.bgBrandSoft,
  },
  actionsRow: {
    flexDirection: "row",
    gap: spacing.sm,
    alignItems: "center",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    maxWidth: "65%",
  },
  tabText: { fontSize: typography.body, color: colors.textSecondary, fontWeight: "700" },
  tabTextActive: { color: colors.brandText },
  tabBadge: {
    marginLeft: spacing.xs,
    backgroundColor: colors.accentSoft,
    color: colors.accent,
    fontSize: typography.micro,
    borderWidth: 1,
    borderColor: "#FFD4C8",
    borderRadius: radius.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    fontWeight: "800",
  },
  buttonMini: {
    backgroundColor: colors.brand,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: radius.pill,
    alignItems: "center",
    minHeight: 40,
    justifyContent: "center",
  },
  buttonText: { color: colors.textOnBrand, fontWeight: "800", fontSize: typography.caption },
  outlineButtonMini: {
    borderWidth: 1.5,
    borderColor: colors.brand,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: radius.pill,
    alignItems: "center",
    backgroundColor: colors.bgBrandSoft,
    minHeight: 40,
    justifyContent: "center",
  },
  outlineButtonText: { color: colors.brandText, fontWeight: "800", fontSize: typography.caption },
  linkTight: { color: colors.brand, fontWeight: "700", fontSize: typography.caption },
  balanceBadge: {
    backgroundColor: colors.bgBrandSoft,
    color: colors.brandText,
    borderRadius: radius.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    fontWeight: "800",
    fontSize: typography.caption,
    borderWidth: 1,
    borderColor: colors.chipBorder,
  },
  balanceMeta: { color: colors.textMuted, fontSize: typography.micro, maxWidth: 100 },
  inlineRow: { flexDirection: "row", gap: spacing.md, marginBottom: spacing.md },
  modalMask: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: colors.bgCard,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    padding: spacing.xl,
    paddingBottom: spacing.xxl,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.card,
  },
  cardTitle: {
    fontWeight: "800",
    fontSize: typography.h4,
    color: colors.textPrimary,
    marginBottom: spacing.sm,
  },
  input: {
    borderWidth: 1.5,
    borderColor: colors.borderSoft,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    marginBottom: spacing.md,
    backgroundColor: colors.bgSoft,
    minHeight: layout.inputMinHeight,
    fontSize: typography.body,
    color: colors.textPrimary,
  },
  card: {
    backgroundColor: colors.bgCard,
    borderRadius: radius.md,
    padding: spacing.lg,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.cardSm,
  },
  loadingText: {
    color: colors.textLoading,
    marginBottom: spacing.md,
    fontWeight: "700",
    fontSize: typography.caption,
    paddingHorizontal: layout.screenPaddingX,
  },
  errorBanner: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warning,
    borderWidth: 1,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    marginHorizontal: layout.screenPaddingX,
    marginBottom: spacing.md,
  },
  errorBannerText: {
    color: "#B45309",
    fontSize: typography.caption,
    fontWeight: "700",
    lineHeight: 20,
  },
  errorActions: { flexDirection: "row", gap: spacing.lg, marginTop: spacing.sm },
  errorActionText: { color: colors.brand, fontSize: typography.caption, fontWeight: "800" },
  });
}

/** Theme-aware app shell styles. */
export function useAppStyles() {
  return useThemedStyles(buildAppStyles);
}
