import { StyleSheet } from "react-native";
import { layout, radius, spacing, typography } from "../../styles/tokens";
import type { ThemeColors } from "../../styles/themes";
import { revealLayerZIndex } from "../../effects/revealLayerZIndex";

export function buildOrderDetailsStyles(colors: ThemeColors) {
  return StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.bgPage },
  gestureShield: {
    ...StyleSheet.absoluteFillObject,
    zIndex: revealLayerZIndex.skipBar,
  },
  container: { paddingBottom: layout.screenPaddingBottom },
  containerTablet: { maxWidth: 720, alignSelf: "center", width: "100%" },
  prizeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    justifyContent: "space-between",
  },
  prizeGridItem: { width: "48%" },
  refundBanner: {
    marginBottom: spacing.md,
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.successSoft,
    borderWidth: 1,
    borderColor: colors.successSoftBorder,
    gap: 4,
  },
  refundBannerTitle: { fontWeight: "800", color: colors.successStrong, fontSize: typography.body },
  refundBannerSub: { color: colors.textSecondary, fontSize: typography.caption },
  integrityBanner: {
    marginBottom: spacing.md,
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.dangerSoft,
    borderWidth: 1,
    borderColor: colors.dangerBorder,
    gap: 4,
  },
  integrityTitle: { fontWeight: "800", color: colors.danger, fontSize: typography.body },
  integritySub: { color: colors.textSecondary, fontSize: typography.caption, lineHeight: 18 },
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.md,
  },
  statusChip: {
    borderWidth: 1,
    borderRadius: radius.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    fontWeight: "800",
    fontSize: typography.caption,
  },
  payAmount: { fontSize: typography.h3, fontWeight: "900", color: colors.textPrimary },
  payDeadline: { marginBottom: spacing.sm, color: colors.brand, fontWeight: "700", fontSize: typography.caption },
  summaryCard: {
    backgroundColor: colors.bgCard,
    borderRadius: radius.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  summaryRow: { flexDirection: "row", justifyContent: "space-between", gap: spacing.md },
  summaryLabel: { color: colors.textSecondary, fontSize: typography.caption },
  summaryValue: { flex: 1, textAlign: "right", color: colors.textPrimary, fontWeight: "700", fontSize: typography.caption },
  idRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: spacing.xs },
  idLabel: { color: colors.textSecondary, fontSize: typography.caption },
  idValue: { color: colors.brand, fontWeight: "700", fontSize: typography.caption },
  logisticsCard: {
    marginTop: spacing.sm,
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.bgSoft,
    borderWidth: 1,
    borderColor: colors.border,
    gap: spacing.xs,
  },
  logisticsTitle: { fontWeight: "800", color: colors.textPrimary, fontSize: typography.caption },
  logisticsStep: { color: colors.textSecondary, fontSize: typography.micro, lineHeight: 18 },
  logisticsHint: { marginTop: spacing.xs, color: colors.textMuted, fontSize: typography.micro },
  actions: { gap: spacing.sm, marginBottom: spacing.lg },
  prizeBlock: { marginTop: spacing.xl, marginBottom: spacing.sm },
  prizeHeaderRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: spacing.sm },
  replayBtnRow: { flexDirection: "row", gap: spacing.xs, flexWrap: "wrap" },
  controlsRow: { flexDirection: "row", gap: 6, flexWrap: "wrap" },
  replayButton: {
    borderWidth: 1,
    borderColor: colors.brand,
    borderRadius: radius.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: 5,
    backgroundColor: colors.bgBrandSoft,
  },
  replayText: { color: colors.brand, fontSize: typography.caption, fontWeight: "700" },
  sessionReplayHint: {
    marginTop: spacing.xs,
    color: colors.textSecondary,
    fontSize: typography.micro,
  },
  replayButtonDisabled: { opacity: 0.45 },
  pendingPaymentHint: {
    marginBottom: spacing.sm,
    color: colors.textMuted,
    fontSize: typography.caption,
  },
  prizeFreezeMask: {
    marginTop: spacing.xl,
    borderRadius: radius.md,
    backgroundColor: colors.bgSoft,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
  },
  prizePlaceholder: {
    padding: spacing.lg,
    gap: spacing.sm,
    opacity: 0.55,
  },
  prizeFrozenHint: {
    color: colors.textMuted,
    fontSize: typography.caption,
  },
  skipRevealBar: {
    position: "absolute",
    top: 56,
    right: spacing.lg,
    zIndex: 2100,
    flexDirection: "row",
    gap: spacing.xs,
    alignItems: "center",
  },
  skipRevealFloating: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.65)",
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  skipRevealText: { color: "#FFFFFF", fontWeight: "800" },
  revealGapBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(6, 8, 18, 0.94)",
    zIndex: revealLayerZIndex.gapBackdrop,
  },
  });
}
